### ISSUE TITLE
Bulk insert functions are currently not supported for Judy1/L

### ISSUE THREAD

**Issue by KerfuffleV2** [toffaletti/rust-judy#1]
For example, the C library has the `JudyLInsArray` function which allows bulk inserts and is much faster than millions of individual calls to insert. In a test I ran with about 300mil inserts, the bulk approach was slightly more than 3 times faster in spite of having to manipulate and sort the entire dataset before inserting.

It does have the restriction that the data must be sorted. Another caveat is that the functions aren't documented or considered officially supported. See: https://www.mail-archive.com/judy-devel@lists.sourceforge.net/msg00373.html

I have a fork that currently supports `JudyLInsArray`: https://github.com/KerfuffleV2/rust-judy/tree/support_judyl_bulk_insert

I could clean it up and add `Judy1InsArray` as well if you'd consider accepting a pull request.

**Comment by toffaletti** [comment]
> I could clean it up and add Judy1InsArray as well if you'd consider accepting a pull request.

Please do. I wrote this code very early (pre-Rust 1.0) before the naming conventions for C bindings of libraries had been established and haven’t really had time or a reason to update it.

**Comment by KerfuffleV2** [comment]
@toffaletti Thanks for the quick reply! I've submitted a pull request. pre-1.0 or not, it seems to have stood the test of time very well!

If it's of interest to you, I was testing some collections over here: https://www.reddit.com/r/rust/comments/mjixno/unscientific_comparison_of_insert_performance_for/

`rust-judy` did very well, and even better using the bulk functions.

**Comment by KerfuffleV2** [comment]
@toffaletti Have you considered making a new release with these changes? It's been 6 years and I expect that discourages people from using the crate even though it still works fine.

**Comment by toffaletti** [comment]
I wanted to get CI working first, which was a good idea because one of the changes you made introduced a memory leak I didn't catch in review: https://github.com/toffaletti/rust-judy/pull/4

**Comment by KerfuffleV2** [comment]
@toffaletti Yikes, nice catch! My apologies, I must have missed then when applying Clippy suggestions. You were definitely correct to take your time and verify everything.
